on:
  workflow_call:

jobs:
  reusable_job:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Get Env Secrets
        run: |
          echo ${{secrets.DEV_ENV_SECRET}} | sed 's/./& /g'
          echo ${{secrets.REPO_SECRET}} | sed 's/./& /g'
      - name: Get Env Variables
        run: |
          echo ${{vars.DEV_ENV_VAR}}
          echo ${{vars.REPO_VAR}}