name: Secret Testing

on:
  push:
    branches:
      - main

jobs:
  secrets-env:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Get Env Secrets
        run: |
          echo ${{secrets.DEV_ENV_SECRET}} | sed 's/./& /g'
          echo ${{secrets.REPO_SECRET}} | sed 's/./& /g'
      - name: Get Env Variables
        run: |
          echo ${{vars.DEV_ENV_VAR}}
          echo ${{vars.REPO_VAR}}

  secrets-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo Secrets
        run: |
          echo ${{secrets.DEV_ENV_SECRET}} | sed 's/./& /g'
          echo ${{secrets.REPO_SECRET}} | sed 's/./& /g'
      - name: Get Repo Variables
        run: |
          echo ${{vars.DEV_ENV_VAR}}
          echo ${{vars.REPO_VAR}}

  secrets-env-reuse:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit